### ISSUE TITLE
When will you release the code? 

### ISSUE THREAD

**Issue by shuluoshu** [gallenszl/CFNet#1]
@gallenszl  hi, nice work! So when will you release the code?

**Comment by gallenszl** [comment]
I am not sure. Maybe at the end of this month.

**Comment by gallenszl** [comment]
Thank you for your concerns about our work. I am really sorry that we may delay one or two weeks to publish our code. After we making our code available, we will inform you through this issue.

**Comment by gallenszl** [comment]
Thank you for your concerns about our work. Code has been released.
