### ISSUE TITLE
the question about accuracy in scene flow datasets

### ISSUE THREAD

**Issue by cjd24-coder** [gallenszl/CFNet#12]
Hello，we test your model on scene flow dataset，but the EPE is only 0.97. Is there something wrong with my use of the code or is the EPE is just 0.97. Thank you very much.

**Comment by gallenszl** [comment]
I am not sure and I will check the record later. Did you get the correct cross-domain generalization accuracy for the pre-training model?

**Comment by cjd24-coder** [comment]
> I am not sure and I will check the record later. Did you get the correct cross-domain generalization accuracy for the pre-training model?
ok，I will check the cross-domain generalization accuracy soon.

**Comment by cjd24-coder** [comment]
> I am not sure and I will check the record later. Did you get the correct cross-domain generalization accuracy for the pre-training model?
OK, I just checked that there is no problem in cross-domain accuracy, so it seems that the accuracy of scene flow is indeed 0.97
