### ISSUE TITLE
Datasets download and placement can be clearer 

### ISSUE THREAD

**Issue by jmuyjl** [gallenszl/CFNet#15]
Sorry for bothering you. Your algorithm is very impressive and helpful. But I did not see clearly how to place the data set in "Data Preparation", can you make the download link more clear, **or put the datasets you use in google_drive**? Thanks a lot for your kind help!

**Comment by gallenszl** [comment]
Hello,  could you tell me which dataset you don't know how to place?

**Comment by gallenszl** [comment]
For KITTI and SceneFlow dataset, you can follow the  ./filenames/sceneflow_train.txt and ./filenames/kitticombine.txt to place the download dataset. 
For Middlebury/ETH3D, you can follow the folder structure we provide to place it

**Comment by jmuyjl** [comment]
Thank you for your reply. In other words, the biggest problem I'm facing now is how to download a dataset (sceneflow, Middlebury / eth3d). I don't know which one to download from every link you give. So can you package the dataset and put it on the cloud disk

**Comment by gallenszl** [comment]
Hello, we use the final pass and disparity of Scene Flow Datasets(FlyingThings3D, Driving and Monkaa). For  Middlebury and eth3d, you can see 4.1 of our main paper for more details. As the dataset is too large (more than 100G),  we do not plan to put it on the cloud disk. Downloading it from the official website may be a better way.

**Comment by jmuyjl** [comment]
@gallenszl How can I test the new picture? I took a bunch of photos (640*480) with my binocular camera and tested it with the model you gave, but there was a size problem during the test. 
`top_pad = 384 - h
right_pad = 1248 - w
assert top_pad > 0 and right_pad > 0`

How can I modify it to test my picture ？

**Comment by gallenszl** [comment]
Hello, you can change the padding size (384,1248) to solve this problem, i.e. 704 * 512

**Comment by jmuyjl** [comment]
@gallenszl Okay, I'll try it. At the same time, I also want to ask, what ratio is this 704 * 512 obtained through?

**Comment by gallenszl** [comment]
Hello, actually it does not matter, the padding can be removed to recover you original image size, i.e., 640*480.
