### ISSUE TITLE
About HITNet

### ISSUE THREAD

**Issue by gangweiX** [gallenszl/CFNet#18]
Your paper is great and efficient. I want to make further improvements on your basis.But I have a doubt, in your paper, HITNet's inference time is 0.015s. But i didn't find official code of HITNet，
how can I test its inference time on my GPUs. Can you give some guidance？Thanks！

**Comment by gallenszl** [comment]
Hello, maybe you can ask this question in the official github website of HITNet:https://github.com/google-research/google-research/tree/master/hitnet.
