### ISSUE TITLE
When will you release the code?

### ISSUE THREAD

**Issue by cjd24-coder** [gallenszl/CFNet#2]
Hello, thank you very much for your excellent work. May I ask when you open source? We need to conduct ablation experiment on your work to verify our versatility in an excellent work like yours.

**Comment by gallenszl** [comment]
Thank you for your concerns about our work. I am really sorry that we may delay one or two weeks to publish our code. After we making our code available, we will inform you through this issue.

**Comment by gallenszl** [comment]
Thank you for your concerns about our work. Code has been released.
