### ISSUE TITLE
TODAY IS July 1st. WILL YOU RELEASE YOUR CODE?

### ISSUE THREAD

**Issue by WellYoungIOE** [gallenszl/CFNet#7]
![image](https://user-images.githubusercontent.com/19660081/124118930-78234080-daa4-11eb-8ffb-5003cc28ed77.png)

**Comment by gallenszl** [comment]
Thank you for your concerns about our work. I am really sorry that we may delay one or two weeks to publish our code. After we making our code available, we will inform you through this issue.

**Comment by gallenszl** [comment]
Thank you for your concerns about our work. Code has been released.
